(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(evil-want-Y-yank-to-eol nil)
 '(package-selected-packages
   '(posframe lsp-mode yaml-mode sphinx-doc import-js grizzl treemacs-persp terminal-here magit-section flycheck-elsa esxml typescript-mode spaceline powerline faceup pyvenv tablist org-category-capture package-lint goto-chg visual-fill-column treemacs pfuture let-alist shrink-path neotree vterm treemacs-magit transient hybrid-mode yasnippet-snippets yapfify xterm-color writeroom-mode winum which-key wgrep web-mode web-beautify uuidgen use-package unfill treemacs-projectile treemacs-evil toc-org tide tagedit symbol-overlay string-inflection ssh-agency spaceline-all-the-icons solarized-theme smex slim-mode sicp shell-pop scss-mode sass-mode rjsx-mode restart-emacs request ranger rainbow-mode rainbow-identifiers racket-mode pytest pyenv-mode py-isort pug-mode prodigy prettier-js popwin pippel pipenv pip-requirements persp-mode pdf-tools pcre2el password-generator paradox ox-hugo overseer origami org-projectile org-pomodoro org-mime org-cliplink open-junk-file ob-restclient ob-http nov nodejs-repl nameless mwim multi-term move-text mmm-mode markdown-toc magit-svn macrostep live-py-mode linum-relative link-hint less-css-mode json-navigator json-mode js2-refactor js-doc ivy-yasnippet ivy-xref ivy-rtags ivy-purpose ivy-hydra indent-guide importmagic impatient-mode ibuffer-projectile hungry-delete hl-todo highlight-parentheses highlight-numbers graphviz-dot-mode google-c-style golden-ratio gnuplot gitignore-templates gitignore-mode gitconfig-mode gitattributes-mode git-timemachine git-messenger git-link ggtags fuzzy font-lock+ flyspell-correct-ivy flycheck-rtags flycheck-pos-tip flycheck-package flx fill-column-indicator expand-region evil-visualstar evil-visual-mark-mode evil-tutor evil-textobj-line evil-surround evil-org evil-numbers evil-nerd-commenter evil-matchit evil-magit evil-lion evil-iedit-state evil-goggles evil-cleverparens evil-anzu eval-sexp-fu eshell-z eshell-prompt-extras esh-help erlang engine-mode emojify emoji-cheat-sheet-plus emmet-mode elisp-slime-nav editorconfig dumb-jump dotenv-mode doom-modeline diminish devdocs deft cython-mode cpp-auto-include counsel-projectile counsel-gtags counsel-css company-web company-statistics company-rtags company-restclient company-reftex company-emoji company-c-headers company-auctex company-anaconda column-enforce-mode color-identifiers-mode centered-cursor-mode blacken bind-map auto-yasnippet auto-highlight-symbol auto-compile aggressive-indent ace-link)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
